// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_XluWsmufqAOoO1ywnolcWTjWHvY84MU',
    appId: '1:692312903496:web:b96840ce971d0ea8ba6d7d',
    messagingSenderId: '692312903496',
    projectId: 'nearby-medical-help',
    authDomain: 'nearby-medical-help.firebaseapp.com',
    storageBucket: 'nearby-medical-help.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYlBIcrWrVEc-ygM7gJZKpx-HpsotQFFc',
    appId: '1:692312903496:android:41b956710f37d017ba6d7d',
    messagingSenderId: '692312903496',
    projectId: 'nearby-medical-help',
    storageBucket: 'nearby-medical-help.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAufQXoyrASlr9ckbsCW2G7I_6-poNCkdg',
    appId: '1:692312903496:ios:6cfbfc5801ae055fba6d7d',
    messagingSenderId: '692312903496',
    projectId: 'nearby-medical-help',
    storageBucket: 'nearby-medical-help.appspot.com',
    iosClientId: '692312903496-l16p3pk641j9tjgdnu9b9f1cfjsat48t.apps.googleusercontent.com',
    iosBundleId: 'com.example.docspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAufQXoyrASlr9ckbsCW2G7I_6-poNCkdg',
    appId: '1:692312903496:ios:6cfbfc5801ae055fba6d7d',
    messagingSenderId: '692312903496',
    projectId: 'nearby-medical-help',
    storageBucket: 'nearby-medical-help.appspot.com',
    iosClientId: '692312903496-l16p3pk641j9tjgdnu9b9f1cfjsat48t.apps.googleusercontent.com',
    iosBundleId: 'com.example.docspot',
  );
}
